### ISSUE TITLE
[Wishlist] skype-wrapper lens

### ISSUE THREAD

**Issue by grissir** [sagetarian/skype-wrapper#53]
Add a Lens and scope to quickly search for contacts

**Comment by grissir** [comment]
I'll code it ;)

**Comment by sagetarian** [comment]
yes please!! i started on this 2 days ago but the quickly code that comes with ubuntu doesn't work OOTB, so i need to figure out the rest. so i'll leave this one to you :) will add you to the list of collaborators .. or you can fork the repo and just send a pull request and i'll do it..

other ideas is:

search for text within messages .. skype for linux has a horrible search feature .. ctrl-f and search for text only brings up the first occurance .. i'm sure this might be harder to do than a contacts category lens but hey ;) get this up and running and i'll collab any other ideas that come to mind :)

**Comment by sagetarian** [comment]
Contact filters can include:

Online contacts, SkypeOut contacts, Recently Conversed with Contacts

i'm just throwing ideas in the air

**Comment by grissir** [comment]
I'll write more scopes when the lens is working. I may wrie it in an extra project but with skype-wrapper as a dependencie has't worked this out yet ;)

**Comment by grissir** [comment]
and by the way it's my first lens so it may need some time :D

**Comment by sagetarian** [comment]
thats cool :) was thinking though that it should be seperate in a "unity-skype-wrapper-lens" project .. i.e for the naming convention of all lenses .. scopes have there own names as well and therefore should be seperate .. when your project is up, i will help with QA or whatever .. have fun :)

then it can be put in the unity-lens PPA and the skype-wrapper PPA .. when running skype-wrapper for the first time, i can bring up a dialog that will ask if they want to install the lens and which scopes to install as well, so that its a seamless process

**Comment by grissir** [comment]
the lens is done, wasn't that hard:
http://github.com/grissir/unity-lens-skype

**Comment by grissir** [comment]
I used your skype-wrapper.svg hope that's ok
